name: pokemon_database

packages:
  - packages/**

sdkPath: '.fvm/flutter_sdk'   

command:
  bootstrap:
    environment:
      sdk: ^3.2.0

scripts:
  clean:
    exec: flutter clean
  pub-get:
    exec: flutter pub get
  pub-upgrade:
    exec: flutter pub upgrade
  analyze:
    exec: flutter analyze
  run-build-runner:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
  test:
    exec: flutter test