name: pokemon_database
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  melos: ^3.4.0

dev_dependencies:
  pedantic_mono:

flutter:
  uses-material-design: true
