name: model
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.2.0

dependencies:
  freezed_annotation: any
  json_annotation: any

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: any
  pedantic_mono: any

