name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: any
  json_annotation: any
  model:
    path: ../model

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: any
  pedantic_mono: any

flutter:
  uses-material-design: true
