name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  freezed_annotation:
  json_annotation:
  model:
    path: ../model
  path:
  path_provider:
  riverpod_annotation:
  roggle:
  sqflite_common_ffi:
  sqflite_common_ffi_web:

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_test:
    sdk: flutter
  freezed: 
  json_serializable:
  pedantic_mono: 
  riverpod_generator: 
  riverpod_lint:

flutter:
  uses-material-design: true

  assets:
    - assets/db/ability.db
    - assets/db/move.db
    - assets/db/pokemon.db
