name: cli
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.2.0

dependencies:
  http: any
  model:
    path: ../model/
  roggle: any

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any

