name: cli
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.2.0

dependencies:
  assets:
    path: ../assets/
  collection:
  http: 
  model:
    path: ../model/

  path:
  sqflite_common_ffi:

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:

