name: check

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 空の .env を作成する。
      # 必要あれば、githubのSECRET情報から値を取得して .env に書き込む。
      - name: Create dot env file
        shell: bash
        run: |
          touch .env
      
      # .fvm/fvm_config.json から flutter のバージョンを取得する。
      # 参考: https://github.com/kuhnroyal/flutter-fvm-config-action#basic-usage
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Run flutter version
        run: flutter --version

      - name: Setup Melos
        uses: bluefireteam/melos-action@v3

      - name: run melos bootstrap
        run: melos bootstrap --sdk-path=${{ runner.tool_cache }}/flutter

      - name: pub get
        run: melos run pub-get --sdk-path=${{ runner.tool_cache }}/flutter

      - name: Install matcher
        run: echo "::add-matcher::.github/analyzer-problem-matcher.json"

      - name: Run flutter analyze
        shell: bash
        run: |
          flutter analyze | tee ./flutter_analyze_report.txt

      - name: Remove matcher
        if: always()
        run: echo "::remove-matcher owner=dart-analyzer::"

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        if: always()
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Danger
        uses: MeilCli/danger-action@v5
        if: always()
        with:
          plugins_file: 'Gemfile'
          install_path: 'vendor/bundle'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
